### ISSUE TITLE
Unable to Connect mainsail to printer ( Serial name/ Serial permissions?)

### ISSUE THREAD

**Issue by xXhoobaXx** [mkuf/prind#142]
hello
thank you for the amazing work 
I am kinda a beginner so I hope you excuse my mistake 

running docker desktop on a Windows machine 
I was able to get everything running with some work and a learning curve 

in print.cfg file 
[mcu]
serial: ..................... 
i am not sure what the serial id here 
i tried many things with no luck 

device manager device instance path is : 
#USB\VID_1D50&PID_614E\31FFD5055241383113780343

i have linux on same machine ( dual boot)
USB serial is : 
#/dev/serial/by-id/usb-Klipper_stm32f103xe_31FFD5055241383113780343-if00

could i be that docker doesn't have permissions to access serial port?

please advice

**Comment by mkuf** [comment]
Hi there, 

this is not possible.  
Docker Desktop on Windows does not support (serial)device pass-through, see docker/for-win#1018 for more Info.  

If you already have linux on your machine I'd suggest installing docker and starting the stack there.  
Otherwise, if you really want to have it running while windows is booted, you may want to use a virtualbox vm with ubuntu installed, pass the device to your vm and run the stack there. 

-Markus
